services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    ports:
      - "8000:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./model:/models
      - ./config:/config
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  api:
    build: .
    container_name: dcc-api
    ports:
      - "8001:8001"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=production
      - OLLAMA_URL=http://ollama:11434
      - API_HOST=0.0.0.0
      - API_PORT=8001
      - LOG_LEVEL=INFO
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  ollama_data:
