services:
  ollama:
    build:
      context: ..
      dockerfile: Dockerfile.ollama
    image: docker-ollama
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      # - ../models:/models
    restart: unless-stopped
    entrypoint: ["/bin/bash", "-c"]
    command: |
      "ollama serve &
       sleep 10 &&
       ollama create phi4-chat -f Modelfile &&
       wait"

  badge-api:
    build:
      context: ..
      dockerfile: Dockerfile
    image: docker-badge-api
    container_name: badge-api
    ports:
      - "8000:8000"
    volumes:
      - ../assets:/app/assets
    environment:
      - OLLAMA_API_URL=http://host.docker.internal:11434/api/generate
    depends_on:
      - ollama
    extra_hosts:              
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  ollama-data:
